name: deathback
version: '${project.version}'
main: net.hotamachisubaru.Deathback
api-version: '1.21'
load: STARTUP
commands:
  back:
    usage: /back
permissions:
  back.teleport:
    usage: /back
    description: 死んだところに戻れます
    default: true
